### ISSUE TITLE
MissingPluginException(No implementation found for method write on channel plugings.it_nomads.com/flutter_secure_storage)

### ISSUE THREAD

**Issue by lrferreiro** [mogol/flutter_secure_storage#183]
Why???

**Comment by koskimas** [comment]
Because you are probably running a widget test, and there's only an implementation for android and iOS, as for basically every other plugin.

**Comment by kurtiev** [comment]
Hi, 
Did u find a solution?  @lrferreiro

**Comment by ykone** [comment]
My problem is solved and I think it is a compatibility issue between plugins. I created a new project and added the plugins one by one. Arrived at the _**flutter_barcode_scanner: ^1.0.2**_ plugin the error appeared. So I just removed it and my app works fine with version 4.1.0 of flutter_secure_storage
Hope this helps other people.

**Comment by juliansteenbakker** [comment]
Closing this because of no activity. Feel free to comment you think this shouldn't be closed.

**Comment by yanctrindade** [comment]
Im trying to write unit tests for my secureStorage class that interacts with the plugin and I still getting the error when running its. What would be the best way to write unit tests and avoid this error?

**Comment by kurtiev** [comment]
Sorry, no.
I didn't work on that after the update of my comment. For me problem was solved.
