### ISSUE TITLE
`containsKey` always returning true

### ISSUE THREAD

**Issue by MichaelM97** [mogol/flutter_secure_storage#338]
I've just started using `flutter_secure_storage` in a new project, for some reason `containsKey` is returning `true` for every key value I give it.

In the below image (showing a debug session) you can see that `containsKey` is returning true even though `readAll` returns an empty map, and I even try deleting the value associated with the key but `containsKey` still returns true. This is running on an iOS simulator.

<img width="593" alt="Screenshot 2021-11-20 at 20 20 18" src="https://user-images.githubusercontent.com/22373058/142739987-80811728-7636-4731-a74f-95e675dfae61.png">

Versions:
* Flutter - `2.5.3`
* Dart - `2.14.4`
* Xcode - `13.0`
* iOS - `15.0`
* flutter_secure_storage - `5.0.2`

**Comment by dustin-graham** [comment]
I encountered the same error but found that it only affects the iPad. All of my iPhone test devices worked as expected but the iPad always returns true.

**Comment by awaisabbasaa11** [comment]
is ther any solution for this problem, I am also having same issue on iPhone but it is working fine on android

**Comment by ToniTornado** [comment]
We make an additional check on the value of the key to work around this issue - if the key is reported to be there, we additionally check if it is not null and not empty. This feels wrong but at least people can use our app again... 🙃

**Comment by ToniTornado** [comment]
@dustin-graham For sure, that should be enough. I checked my code again and I also just `read` the value and check for `null`. In some rare case I got an empty string so I am checking for that too. But this might be specific to my app. I also checked the implementation of `containsKey` in this plugin for a possible fix but I was not able to understand that keychain ObjC code that is bridging to some other lib.... 🙈

**Comment by NengSyle007** [comment]
I got the same issue contains key always return true.

I try to testing with multiple version.

flutter_secure_storage - 5.0.0 & 5.0.1 & 5.0.2
Flutter - 2.8.1
Dart - 2.15.1
Xcode - 13.2
iOS - 15.2

**Comment by HugoHeneault** [comment]
Same issue here, using latest pub version :(

We've also removed `containsKey` usage and replace it by a null check on `read`.

```
flutter doctor                                                                                                                                                                                                                                ─╯


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

• No issues found!

```

**Comment by vanlooverenkoen** [comment]
This is a major bug for such a big package. @juliansteenbakker or @mogol can we timeline on when this can be fixed?

**Comment by comatory** [comment]
This has caused really nasty bug with our iOS releases, took me few hours to find this out since the problem occurred only on devices that never had previous builds.
I can confirm v4 does not have this problem. Also replaced `containsKey` with check on `null` value by using `read`.

**Comment by sems** [comment]
> downgrading to this version : `flutter_secure_storage: ^4.2.1`

Same here, our development-team choose the same option - too bad, since we can't have an the other improvements which came with upgrade to version > `5.x.x`

**Comment by chengdujin** [comment]
Same issue here. Guys, this bug was reported Nov. last year. Has it been solved?

**Comment by farkerhaiku** [comment]
I'm sure if it had been solved there would be a bug fix release. Last I checked, open source maintainers weren't paid for their efforts, so the demanding tone is most likely not going to get the results you're looking for.

**Comment by juliansteenbakker** [comment]
I am aware of this issue as well as some other issues with this package. I'm trying to free up some time to work on this but i'm working on more packages that just this one. Like I said in other issues, I encourage people to try and fix it them self and i am very much open for PR's that could fix this problem.

**Comment by nank1ro** [comment]
Seems like this bug has been introduced with the version 5.0.0-beta.5 with the new `containsKey` method.
As a workaround you can go back to the previous implementation using:
```dart
_flutterSecureStorage.read(key: 'key') != null
```
instead of 
```dart
_flutterSecureStorage.containsKey(key: 'key')
```

**Comment by galizhan** [comment]
Faced the same bug

**Comment by sems** [comment]
> @[juliansteenbakker](https://github.com/juliansteenbakker) juliansteenbakker mentioned this issue [on 24 Aug](https://github.com/mogol/flutter_secure_storage/issues/338#ref-pullrequest-1349110179)
https://github.com/mogol/flutter_secure_storage/pull/437

@juliansteenbakker Do you have any indication when this will be merged into the master branch?

**Comment by juliansteenbakker** [comment]
Sorry for the delay, i've been busy with moving to a new house and last week i've been hit by covid. I think i finished all the code but i did not have any time to test it.

If someone has time to test my code i'd be very happy. After some verification i can merge and release a new version.

**Comment by juliansteenbakker** [comment]
I have released v6.1.0-beta.1 which probably fixes this issue. Can you please check, and if there is any error comment on this issue?

**Comment by Adam-Langley** [comment]
Hi @juliansteenbakker - I've tried the beta - it does not resolve the issue.

**Comment by localboss-git** [comment]
Same bug, crazy in such a big package

**Comment by localboss-git** [comment]
> As a workaround you can go back to the previous implementation using:
> 
> ```dart
> (await _flutterSecureStorage.read(key: 'key')) != null
> ```
> 
> instead of
> 
> ```dart
> await _flutterSecureStorage.containsKey(key: 'key')
> ```

At least this works

**Comment by SexyBeast007** [comment]
Well, I'm glad I searched and found this. I ended up switching to a null check of .read() and got some code working. Then ran into the same issue again further down the execution sequence, and felt it was an issue. Found this and it's good to know for sure!

I agree this should NOT be an issue for such an important and large library. Null checks and empty checks are sloppy, can this be fixed? Believe me, I would help if I was experienced enough to do so... Up to you geniuses, someone get this puppy fixed ;)

**Comment by juliansteenbakker** [comment]
I understand this is still a problem, and it is not that i don't want to fix this, but rather i have some other plugins that require more work right now.

@Adam-Langley ofcourse your welcome to sponsor me, but for me its a problem of time and not motivation/money. I have a fulltime job besides working on these plugins and the december months are more busy than others. 

As always im open for PR's with a fix. I'll also take another look into this tomorrow to see if i can come up with anything else.

**Comment by Adam-Langley** [comment]
Hey @juliansteenbakker - absolutely see your position. Not criticising at all.
I wonder if perhaps just integrating the pure-dart workaround into your wrapper code, until you have time to write your preferred approach (which I assume is more complex, and involves native code)? 
That way, you get to put it to bed for a little while, and it will tripping up the newbies?

**Comment by juliansteenbakker** [comment]
Ill see if i can try and fix it on the native side. If not, ill implement this workaround as a quick fix.

**Comment by Adam-Langley** [comment]
Thanks @juliansteenbakker - that would be awesome. Thank you for giving it a try - can't ask for much more than that!
Throwing some appreciation your way :)

**Comment by juliansteenbakker** [comment]
Thanks !! Really appreciate it 😁

**Comment by juliansteenbakker** [comment]
It turned out the sharedPreference instance was created multiple times in Android. This was causing lots of problems with not only containsKey, but also trying to read the value using the key. I have fixed these issues, together with containsKey problems on macOS in version 7.0.0. Please check it out and let me know if this fixes the issues 😄
