### ISSUE TITLE
The specified item could not be found in the keychain

### ISSUE THREAD

**Issue by gianlucainnocente** [mogol/flutter_secure_storage#709]
Hello,
after yesterday's update (9.1.1) we are encountering this error when trying to read secure storage only on ios:

`Unhandled Exception: PlatformException(Unexpected security result code, Code: -25300, Message: The specified item could not be found in the keychain., -25300, null)`

How can we solve that?
Thank you

**Comment by techouse** [comment]
Same here.

**Comment by SpykeyRev** [comment]
Same here.

**Comment by dilshd** [comment]
same here

**Comment by dilshd** [comment]
Same here, what's the solution?

**Comment by JgomesAT** [comment]
SAme here with the last version 9.1.1

**Comment by techouse** [comment]
> and If I back to the previous version the problem is not solved, and now I can't run the app

Huh? Just revert your `pubspec.lock` to the previous state. That will fix it.,

**Comment by techouse** [comment]
> Same here, what's the solution?

Don't upgrade.

**Comment by nausharipov** [comment]
Same here. Fixed my version to: `flutter_secure_storage: 9.0.0`.

**Comment by ztaylor54** [comment]
Submitted a fix for this in #710. 

Looks like the platform function `readAll` was updated to check for empty keys, but `read` wasn't. Until my fix is tested and merged, the best bet would be to pin an earlier version.

**Comment by ztaylor54** [comment]
For those who get here and need a temporary workaround for version 9.1.1, `read` is the problem, `readAll` works fine. You just need to do the key lookup yourself:

```dart
final secureStore = const FlutterSecureStorage();

// Not working in 9.1.1
final key = await secureStore.read(key: "some_key"); 

// Workaround -- `key` will be `null` if not present
final key = await secureStore.readAll()["some_key"];
```

**Comment by mNouh94** [comment]
> For those who get here and need a temporary workaround for version 9.1.1, `read` is the problem, `readAll` works fine. You just need to do the key lookup yourself:
> 
> ```dart
> final secureStore = const FlutterSecureStorage();
> 
> // Not working in 9.1.1
> final key = await secureStore.read(key: "some_key"); 
> 
> // Workaround -- `key` will be `null` if not present
> final key = (await secureStore.readAll())["some_key"];
> ```

This works fine for now, Thank you

**Comment by dilshd** [comment]
> > Same here, what's the solution?
> 
> Don't upgrade.

now i have flutter_secure_storage: ^9.0.0, but still showing same error

**Comment by nausharipov** [comment]
@dilshd specify the version: `flutter_secure_storage: 9.0.0`

**Comment by dilshd** [comment]
> @dilshd specify the version: `flutter_secure_storage: 9.0.0`

i did, but still same.

**Comment by dilshd** [comment]
> For those who get here and need a temporary workaround for version 9.1.1, `read` is the problem, `readAll` works fine. You just need to do the key lookup yourself:
> 
> ```dart
> final secureStore = const FlutterSecureStorage();
> 
> // Not working in 9.1.1
> final key = await secureStore.read(key: "some_key"); 
> 
> // Workaround -- `key` will be `null` if not present
> final key = (await secureStore.readAll())["some_key"];
> ```

what about secureStore.delete?

**Comment by ztaylor54** [comment]
> > @dilshd specify the version: `flutter_secure_storage: 9.0.0`
> 
> i did, but still same.

You might need to do a `flutter clean` and rebuild so the downgrade actually happens. As far as the `delete` method, I am unsure. It's entirely possible that method is bugged as well, in which case the package maintainer can hopefully weigh in with a workaround and/or a fix.

**Comment by dilshd** [comment]
> > > @dilshd specify the version: `flutter_secure_storage: 9.0.0`
> > 
> > 
> > i did, but still same.
> 
> You might need to do a `flutter clean` and rebuild so the downgrade actually happens. As far as the `delete` method, I am unsure. It's entirely possible that method is bugged as well, in which case the package maintainer can hopefully weigh in with a workaround and/or a fix.
is it possible like this ?
final key = (await secureStore.deleteAll())["some_key"];

**Comment by dilshd** [comment]
> > > @dilshd specify the version: `flutter_secure_storage: 9.0.0`
> > 
> > 
> > i did, but still same.
> 
> You might need to do a `flutter clean` and rebuild so the downgrade actually happens. As far as the `delete` method, I am unsure. It's entirely possible that method is bugged as well, in which case the package maintainer can hopefully weigh in with a workaround and/or a fix.

is it possible like this ?
final key = (await secureStore.deleteAll())["some_key"];

**Comment by ztaylor54** [comment]
> > > > @dilshd specify the version: `flutter_secure_storage: 9.0.0`
> > > 
> > > 
> > > i did, but still same.
> > 
> > 
> > You might need to do a `flutter clean` and rebuild so the downgrade actually happens. As far as the `delete` method, I am unsure. It's entirely possible that method is bugged as well, in which case the package maintainer can hopefully weigh in with a workaround and/or a fix.
> 
> is it possible like this ? final key = (await secureStore.deleteAll())["some_key"];

Only if you are okay with deleting all keys. `deleteAll` deletes all keys you have stored, and doesn't return anything, so you wouldn't need the `["some_key"]` part.

**Comment by dilshd** [comment]
> > > > > @dilshd specify the version: `flutter_secure_storage: 9.0.0`
> > > > 
> > > > 
> > > > i did, but still same.
> > > 
> > > 
> > > You might need to do a `flutter clean` and rebuild so the downgrade actually happens. As far as the `delete` method, I am unsure. It's entirely possible that method is bugged as well, in which case the package maintainer can hopefully weigh in with a workaround and/or a fix.
> > 
> > 
> > is it possible like this ? final key = (await secureStore.deleteAll())["some_key"];
> 
> Only if you are okay with deleting all keys. `deleteAll` deletes all keys you have stored, and doesn't return anything, so you wouldn't need the `["some_key"]` part.

But i need to delete separately.

**Comment by ztaylor54** [comment]
> > > > > > @dilshd specify the version: `flutter_secure_storage: 9.0.0`
> > > > > 
> > > > > 
> > > > > i did, but still same.
> > > > 
> > > > 
> > > > You might need to do a `flutter clean` and rebuild so the downgrade actually happens. As far as the `delete` method, I am unsure. It's entirely possible that method is bugged as well, in which case the package maintainer can hopefully weigh in with a workaround and/or a fix.
> > > 
> > > 
> > > is it possible like this ? final key = (await secureStore.deleteAll())["some_key"];
> > 
> > 
> > Only if you are okay with deleting all keys. `deleteAll` deletes all keys you have stored, and doesn't return anything, so you wouldn't need the `["some_key"]` part.
> 
> But i need to delete separately.

Then I suggest pinning the version of this package to 9.0.0 or earlier, until it works for you without errors.

**Comment by dilshd** [comment]
> > > > > > > @dilshd specify the version: `flutter_secure_storage: 9.0.0`
> > > > > > 
> > > > > > 
> > > > > > i did, but still same.
> > > > > 
> > > > > 
> > > > > You might need to do a `flutter clean` and rebuild so the downgrade actually happens. As far as the `delete` method, I am unsure. It's entirely possible that method is bugged as well, in which case the package maintainer can hopefully weigh in with a workaround and/or a fix.
> > > > 
> > > > 
> > > > is it possible like this ? final key = (await secureStore.deleteAll())["some_key"];
> > > 
> > > 
> > > Only if you are okay with deleting all keys. `deleteAll` deletes all keys you have stored, and doesn't return anything, so you wouldn't need the `["some_key"]` part.
> > 
> > 
> > But i need to delete separately.
> 
> Then I suggest pinning the version of this package to 9.0.0 or earlier, until it works for you without errors.

i changed to 9.0.0 in pubspec.lock & pubspec.yaml, i the error still showing down.

**Comment by ztaylor54** [comment]
@dilshd delete `pubspec.lock`, run `flutter clean`, then run `flutter pub get` and then rebuild the project

**Comment by dilshd** [comment]
> @dilshd delete `pubspec.lock`, run `flutter clean`, then run `flutter pub get` and then rebuild the project

It works, thanks.

**Comment by JgomesAT** [comment]
I can see this:

Event Data 10
Language
es-es

Page Location
https://www.andorratelecom.ad/botiga/

Page Title
Andorra Telecom

Screen Resolution
1920x1080
Session Count
1

Session ID
1715330811

ep.cookie_consent
granted

ep.firebase_screen
Dashboard_Particular

ep.firebase_screen_class
minified:DE

ep.origin
firebase

these two events are related to the name and class of screen_view:

ep.firebase_screen
Dashboard_Particular

ep.firebase_screen_class
minified:DE

I don't understand the class minified:DE this Is not a class of my project

**Comment by abibiano** [comment]
In macOS, I had to pin also the flutter_secure_storage_macos package  in pubspec.yaml

```
dependency_overrides:
  flutter_secure_storage: 9.1.1
  flutter_secure_storage_macos: 3.0.1
```

**Comment by techouse** [comment]
> In macOS, I had to pin also the flutter_secure_storage_macos package in pubspec.yaml
> 
> ```
> dependency_overrides:
>   flutter_secure_storage: 9.1.1
>   flutter_secure_storage_macos: 3.0.1
> ```

More like
```yaml
dependency_overrides:
  # temporary fix for https://github.com/mogol/flutter_secure_storage/issues/709
  flutter_secure_storage: 9.0.0
  flutter_secure_storage_linux: 1.2.0
  flutter_secure_storage_macos: 3.0.1
  flutter_secure_storage_platform_interface: 1.0.2
  flutter_secure_storage_windows: 3.0.0
  flutter_secure_storage_web:  1.2.0
```

**Comment by earthManMan** [comment]
write도 마찬가지인데 해결 하려면 어떻게 해야돼??

**Comment by perdomon** [comment]
The roll back to 9.0.0 worked great after flutter clean. Is there a way to follow the issue on Github so I can update the package once a fix is released?

**Comment by KOREAparksh** [comment]
Does the OS use cache internally when using Keychain? There is no problem when I access the Key value already in use before the package update, but when I read it again after calling the remove method, a problem occurs.

**Comment by juliansteenbakker** [comment]
Hi all, i am reviewing #710 and will release a fix later today

**Comment by sAtluna** [comment]
Thanks @juliansteenbakker. Looking forward to the fix. Rolling back to 9.0.0 fixed the issue for me

**Comment by mellowcello77** [comment]
I'm on 9.0.0 and getting the same error.

**Comment by hasunperera** [comment]
Getting the same error, I'm already on version 9.0.0 and I did not upgrade to version 9.1.1

**Comment by byronweiss** [comment]
> The roll back to 9.0.0 worked great after flutter clean. Is there a way to follow the issue on Github so I can update the package once a fix is released?

Top Right - Notifications - Subscribe

**Comment by EpiSayLaCata** [comment]
This is an odd problem. I'm in 9.0.0 since months and didn't do the upgrade and now I've the error only on the simulator.

I just changed my macbook yesterday so is it really this lib problem ? 

ps : workaround seems to be working.

**Comment by hantrungkien** [comment]
> > For those who get here and need a temporary workaround for version 9.1.1, `read` is the problem, `readAll` works fine. You just need to do the key lookup yourself:
> > ```dart
> > final secureStore = const FlutterSecureStorage();
> > 
> > // Not working in 9.1.1
> > final key = await secureStore.read(key: "some_key"); 
> > 
> > // Workaround -- `key` will be `null` if not present
> > final key = (await secureStore.readAll())["some_key"];
> > ```
> 
> what about secureStore.delete? i got same problem when i delete.

it works for me:

```dart
    if (await _secureStorage.containsKey(key: _accessTokenKey)) {
      await _secureStorage.delete(key: _accessTokenKey);
    }
```

**Comment by ercantomac** [comment]
Seems like the issue is fixed with the latest version (9.2.0)

**Comment by techouse** [comment]
> Seems like the issue is fixed with the latest version (9.2.0)

After upgrading to v9.2.0 I still experience this error. After restarting the app the session is not restored because the token is not there.

**Comment by g123k** [comment]
It seems that the sub-dependencies are not updated (eg: for macOS).
The last version was 7 days ago.

**Comment by juliansteenbakker** [comment]
> It seems that the sub-dependencies are not updated (eg: for macOS). The last version was 7 days ago.

The macOS implementation was never updated to match the iOS behaviour. I have updated this just now and am releasing this asap.

**Comment by juliansteenbakker** [comment]
I have released v9.2.1 with these fixes.

**Comment by techouse** [comment]
> @techouse I am unable to reproduce this behavior, can you please provide more detail? It would also be a good idea to run a `flutter clean` and fully rebuild.

Hey @ztaylor54 I did cleaned it and updated the pods. I'm still having the same problem with v9.2.1.

I did some tests and it looks like using **v9.2.1** `await secureStorage.readAll()` returns an empty Map `{}`, however, `await secureStorage.real(key: 'someKeyName')` returns that key's value.

- OS: iOS v17.4.1
- Physical Device: iPhone 13 Pro
- Flutter ver: 3.19.6

The keychain was populated with
- `flutter_secure_storage: 9.0.0`
- `flutter_secure_storage_macos: 3.0.1`
- `flutter_secure_storage_platform_interface: 1.0.2`

 I used this simple Dart code.

```dart
final Map<String, String> secureData = await secureStorage.readAll();
print('is secureData empty: ${secureData.isEmpty}');
// call readAll again explicitly
print('stored username via readAll: ${(await secureStorage.readAll())['username']}');
print('stored username via read: ${await secureStorage.read(key: 'username')}');
```

### Using v9.0.0

- `flutter_secure_storage: 9.0.0`
- `flutter_secure_storage_macos: 3.0.1`
- `flutter_secure_storage_platform_interface: 1.0.2`

I get

```
flutter: is secureData empty: false
flutter: stored username via readAll: foo@bar.baz
flutter: stored username via read: foo@bar.baz
```

### Using v9.2.1

- `flutter_secure_storage: 9.2.1`
- `flutter_secure_storage_macos: 3.1.1`
- `flutter_secure_storage_platform_interface: 1.1.2`

I get

```
flutter: is secureData empty: true
flutter: stored username via readAll: null
flutter: stored username via read: foo@bar.baz
```

**Comment by techouse** [comment]
@juliansteenbakker @ztaylor54 I submitted a PR fixing this https://github.com/mogol/flutter_secure_storage/pull/719

It seems that somehow the accessibility for `readAll` was explicitly set to `nil`, which is not the case for `read`.

**Comment by lance-mlabs** [comment]
FYI, I've experienced this issue writing a string via `_storage.write(key: key, value: value);` with the latest version `9.2.2`.

**Comment by HoangDinhTho** [comment]
this issue still with the latest version 9.2.2 when writing secureStorage.write( key: key, value: value,
        aOptions: AndroidOptions( encryptedSharedPreferences: true ),
        iOptions: IOSOptions(accessibility: KeychainAccessibility.unlocked_this_device));

**Comment by iosephmagno** [comment]
Yes we are hit by this issue too, version 9.2.2.

**Comment by iosephmagno** [comment]
in our case issue occurred the first time `FlutterSecureStorage.write` was called. We now must better debug, coz it could happen again.

```
[ERROR: flutter/runtime/dart_vm_initializer.ce(41)] Unhandled Exception: PlatformException(Unexpected security result code, Code: -25300, Message: The sp ecified item could not be found in the keychain., -25300, null)
#0
StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#1
MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
‹asynchronous suspension>
#2 FlutterSecureStorage.write (package:flutter_secure_storage/flutter_secure_storage.dart:114)
‹asynchronous suspension>
```

**Comment by pushpendraKh** [comment]
I am also facing this for some of our users not all on 9.2.2. Anyone why it's happening? And also it is happening for some keys not all.

**Comment by hantrungkien** [comment]
A workaround solution:

```dart
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:synchronized/synchronized.dart';

class AuthCache {

  static const _accessTokenKey = "ACCESS_TOKEN_KEY";

  final FlutterSecureStorage _secureStorage;

  final _accessTokenLock = Lock();

  AuthCache._()
      : _secureStorage = const FlutterSecureStorage(
    aOptions: AndroidOptions(
      encryptedSharedPreferences: true,
    ),
  );

  Future<void> setAccessToken(String accessToken) async {
    await _accessTokenLock.synchronized(() async {
      await _secureStorage.write(key: _accessTokenKey, value: accessToken);
    });
  }
}
```

**Comment by hamada147** [comment]
Sometimes, I also get the crash using 9.2.2.

**Comment by Sprechen** [comment]
We are also experimenting this issue with the 9.2.2 version, during writing:
```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: PlatformException(Unexpected security result code, Code: -25300, Message: The specified item could not be found in the keychain., -25300, null)
flutter:
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message\_codecs.dart:646:7)
message\_codecs.dart:646
#1 MethodChannel.\_invokeMethod (package:flutter/src/services/platform\_channel.dart:334:18)
platform\_channel.dart:334
<asynchronous suspension>
#2 FlutterSecureStorage.write (package:flutter\_secure\_storage/flutter\_secure\_storage.dart:114:7)
flutter\_secure\_storage.dart:114
<asynchronous suspension>
#3 StorageService.saveSecure (package:fanta\_app/services/storage-service.dart:61:5)
storage-service.dart:61
<asynchronous suspension>
```

So please, it doesn't seem fixed.
It happens randomly, both on the simulator and real devices

**Comment by gopelkujo** [comment]
Still exists when executed `deleteAll()` in iOS with `flutter_secure_storage: ^9.2.4`:

`PlatformException(Unexpected security result code, Code: -25299, Message: The specified item already exists in the keychain., -25299, null)`

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.97.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

**Comment by jay-simformsolutions** [comment]
I am using flutter_secure_storage: 9.2.4 and still this issue persist. Still anyone facing this issue?

!!! SYNC UP FATAL EXCEPTION !!!
Error: PlatformException(Unexpected security result code, Code: -25308, Message: User interaction is not allowed., -25308, null)
StackTrace: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:370)
<asynchronous suspension>
#2      FlutterSecureStorage.write (package:flutter_secure_storage/flutter_secure_storage.dart:114)
<asynchronous suspension>
#3      SecureStorageHelper.setRecipientsEmailsForLogs (package:e_demand/utils/secure_storage_helper.dart:70)
<asynchronous suspension>
#4      HomeScreenStoreBase._getAllSystemConfig (package:e_demand/modules/home/home_screen_store.dart:720)
<asynchronous suspension>
