### ISSUE TITLE
 requires js ^0.6.3 depends on js ^0.7.1

### ISSUE THREAD

**Issue by Ali-Solak** [mogol/flutter_secure_storage#728]
Any plans to update the js deps with the web package. It's at odds with other dependencies for me

```
flutter_secure_storage ^9.1.1 which depends on flutter_secure_storage_web ^1.2.1, every version of __
  from path requires flutter_secure_storage_web ^1.2.1.
Because flutter_secure_storage_web 1.2.1 depends on js ^0.6.3 and no versions of flutter_secure_storage_web match >1.2.1 <2.0.0, flutter_secure_storage_web ^1.2.1
  requires js ^0.6.3.
Thus, every version of  from path requires js ^0.6.3.
And because pdf_render >=1.4.7 depends on js ^0.7.1
```

**Comment by Daniel-Cong** [comment]
A lot of my packages got stuck on old version as well, because flutter_secure_storage defined an old outdated js package as it's dependency.

**Comment by Ali-Solak** [comment]
I guess this should be resolved with the release of the 2.0.0 web package, since it's going to use the web package without the js dep

flutter_secure_storage_web: ^2.0.0-beta.1

**Comment by itismejy** [comment]
still not solved yet. using this:
  flutter_secure_storage: ^9.2.1
  flutter_secure_storage_web: ^2.0.0-beta.1

**Comment by AlexMobile-l** [comment]
Because ybot depends on flutter_secure_storage ^9.2.1 which depends on flutter_secure_storage_web ^1.2.1, flutter_secure_storage_web ^1.2.1 is required.
So, because ybot depends on flutter_secure_storage_web ^2.0.0-beta.1, version solving failed.

**Comment by AlexMobile-l** [comment]
It looks like it's working. Thank you!
